// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAT75zA9lUEn23t-6rT6AtKx-0L86Xhws',
    appId: '1:559985935201:web:c60923cbbead4db18bbb20',
    messagingSenderId: '559985935201',
    projectId: 'my-app-firebase',
    authDomain: 'my-app-firebase-df150.firebaseapp.com',
    storageBucket: 'my-app-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEMWgoL25JBl6Ixf82ExRMriLQHevma4',
    appId: '1:559985935201:android:c033314a9a12c1658bbb20',
    messagingSenderId: '559985935201',
    projectId: 'my-app-firebase',
    storageBucket: 'my-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9FQn_mvrtNu5xXNaBuXd3MnyCbMlVG0',
    appId: '1:559985935201:ios:8cc2bdba4a2f0a198bbb20',
    messagingSenderId: '559985935201',
    projectId: 'my-app-firebase',
    storageBucket: 'my-app-firebase.appspot.com',
    iosClientId:
        '559985935201-rjaq8gg3d62sp3q3fqj5uefldvu0p1m9.apps.googleusercontent.com',
    iosBundleId: 'com.izelon.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL9FQn_mvrtNu5xXNaBuXd3MnyCbMlVG0',
    appId: '1:559985935201:ios:8cc2bdba4a2f0a198bbb20',
    messagingSenderId: '559985935201',
    projectId: 'my-app-firebase',
    storageBucket: 'my-app-firebase.appspot.com',
    iosClientId:
        '559985935201-rjaq8gg3d62sp3q3fqj5uefldvu0p1m9.apps.googleusercontent.com',
    iosBundleId: 'com.izelon.mynote',
  );
}
